env:
  IMAGE_ID: xcode-16.2-macos-14.7.1-v1
agents:
  queue: 'mac'

steps:
  - label: "🧪 Build and Test (iPhone 12 Simulator)"
    command: .buildkite/commands/run-tests.sh 'iPhone 16'

  - label: "🧪 Build and Test (iPad Pro 13-inch (M4) Simulator)"
    command: .buildkite/commands/run-tests.sh 'iPad Pro 13-inch (M4)'
