env:
  IMAGE_ID: xcode-16.2-macos-14.7.1-v1
agents:
  queue: 'mac'

steps:
  - label: "🧪 Build and Test (iPhone 16 Simulator)"
    command: .buildkite/commands/run-tests.sh 'iPhone 16'

  # Some tests will fail on an bigger screen than this because they check for out of screen elements
  - label: "🧪 Build and Test (iPad Pro 11-inch (M4) Simulator)"
    command: .buildkite/commands/run-tests.sh 'iPad Pro 11-inch (M4)'
